- hosts: masters[0]
  gather_facts: false
  vars_prompt:

    - name: username
      prompt: Username
      private: false

  tasks:

    - name: Delete system user
      include_tasks: tasks/system_user.yaml
      vars:
        state: absent

    - name: Delete dashboard user
      include_tasks: tasks/dashboard_user.yaml
      vars:
        state: absent

    - name: Delete kubectl user
      include_tasks: tasks/kubectl_user.yaml
      vars:
        state: absent
