- hosts: masters[0]
  gather_facts: false
  tasks:

    - name: Install cert-manager with Helm
      kubernetes.core.helm:
        namespace: cert-manager
        create_namespace: true
        chart_repo_url: https://charts.jetstack.io
        chart_ref: cert-manager
        chart_version: v1.16.3
        name: cert-manager
        values:
          crds:
            enabled: true

    - name: Create letsencrypt-staging issuer
      kubernetes.core.k8s:
        resource_definition:
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: letsencrypt-staging
          spec:
            acme:
              server: https://acme-staging-v02.api.letsencrypt.org/directory
              email: gabriel.pelouze@lifewatch.eu
              privateKeySecretRef:
                name: letsencrypt-staging
              solvers:
                - http01:
                    ingress:
                      ingressClassName: nginx

    - name: Create letsencrypt-prod issuer
      kubernetes.core.k8s:
        resource_definition:
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: letsencrypt-prod
          spec:
            acme:
              server: https://acme-v02.api.letsencrypt.org/directory
              email: gabriel.pelouze@lifewatch.eu
              privateKeySecretRef:
                name: letsencrypt-prod
              solvers:
                - http01:
                    ingress:
                      ingressClassName: nginx