- hosts: masters[0]
  gather_facts: no
  tasks:

    - name: Create namespace
      k8s:
        kind: Namespace
        name: ingress-nginx

    - name: Create directory self-signed SSL certificate
      file:
        path: ingress_self_signed_cert
        state: directory

    - name: Check for self-signed SSL certificate
      stat:
        path: ingress_self_signed_cert/cert.pem
      register: check_ssl_cert

    - name: Create self-signed SSL certificate
      shell: openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/CN=Kubernetes Ingress Controller Fake Certificate" -keyout ingress_self_signed_cert/key.pem -out ingress_self_signed_cert/cert.pem
      when: not check_ssl_cert.stat.exists

    - name: Store SSL certificate
      shell: kubectl -n ingress-nginx create secret tls ingress-self-signed-tls --key ingress_self_signed_cert/key.pem --cert ingress_self_signed_cert/cert.pem
      when: not check_ssl_cert.stat.exists

    - name: Install ingress-nginx with Helm
      kubernetes.core.helm:
        namespace: ingress-nginx
        create_namespace: true
        chart_repo_url: https://kubernetes.github.io/ingress-nginx
        chart_ref: ingress-nginx
        chart_version: v4.12.0
        name: ingress-nginx
        values:
          controller:
            metrics:
              enabled: true
            podAnnotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: 10254
            service:
              nodePorts:
                http: 32080
                https: 32443
                tcp:
                  "8080": 32808
              type: NodePort
            extraArgs:
              default-ssl-certificate: "ingress-nginx/ingress-self-signed-tls"
          ingressClassResource:
            default: true
