- hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade system
      apt:
        upgrade: full

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Install dependencies
      package:
        state: present
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - git
          - gnupg2
          - jq
          - python3
          - python3-pip
          - software-properties-common
          - vim
          - wget

    - name: Install python packages
      pip:
        name:
          - kubernetes  # for ansible kubernetes.core collection
