- hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Get distribution name
      shell: '. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}"'
      register: dist

    - name: Get arch
      shell: dpkg --print-architecture
      register: arch

    - name: Add Docker Repository
      apt_repository:
        repo: 'deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ dist.stdout }} stable'
        state: present
      register: repo

    - name: Update apt cache
      apt:
        update_cache: yes
      when: repo.changed

    - name: Install containerd
      package:
        state: present
        name:
          - containerd.io
      register: install

    - name: Generate default containerd configuration
      shell: |
        containerd config default > /etc/containerd/config.toml
      when: install.changed

    - name: Configure containerd
      lineinfile:
        path: /etc/containerd/config.toml
        line: '{{ item.line }}'
        regexp: '{{ item.regexp }}'
        backrefs: true
      with_items:
        - line: '\1SystemdCgroup = true'
          regexp: '^(\s*)SystemdCgroup = (true|false)$'
      when: install.changed

    - name: Configure containerd volumes
      lineinfile:
        path: /etc/containerd/config.toml
        line: '{{ item.line }}'
        regexp: '{{ item.regexp }}'
        backrefs: true
      with_items:
        - line: '\1root = "{{ runtime_path }}/containerd_root"'
          regexp: '^(\s*)root = ".*"$'
        - line: '\1state = "{{ runtime_path }}/containerd_state"'
          regexp: '^(\s*)state = ".*"$'
      when: 'install.changed and (runtime_path | default("", true) | trim != "")'

    - name: Restart containerd
      service:
        name: containerd
        enabled: true
        state: restarted
      when: install.changed
