- hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: '0644'

    - name: Get distribution name
      shell: 'echo $(lsb_release -cs)'
      register: dist

    - name: Get arch
      shell: dpkg --print-architecture
      register: arch

    - name: Add Docker Repository
      apt_repository:
        repo: 'deb [arch={{ arch.stdout }}] https://download.docker.com/linux/ubuntu {{ dist.stdout }} stable'
        state: present
      register: repo

    - name: Update apt cache
      apt:
        update_cache: yes
      when: repo.changed

    - name: Install containerd
      package:
        state: present
        name:
          - containerd.io
      register: install

    - name: Configure containerd
      shell: |
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
      when: install.changed

    - name: Restart containerd
      service:
        name: containerd
        enabled: true
        state: restarted
      when: install.changed
