- hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Install dependencies
      package:
        state: present
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - git
          - gnupg2
          - jq
          - python3
          - python3-pip
          - software-properties-common
          - vim
          - wget

    - name: Install python packages
      pip:
        name:
          - kubernetes  # for ansible kubernetes.core collection
