- hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Add Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes.asc
        mode: '0644'

    - name: Add Kubernetes repository
      apt_repository:
        repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /'
        state: present
      register: repo

    - name: Update apt cache
      apt:
        update_cache: yes
      when: repo.changed

    - name: Install kube
      package:
        state: present
        name:
          - kubelet
          - kubeadm
          - kubectl

    - name: Hold kubeadm
      dpkg_selections:
        name: '{{ item }}'
        selection: hold
      with_items:
        - kubelet
        - kubeadm
        - kubectl
