- hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade system
      apt:
        upgrade: full

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot
      reboot:
      when: reboot_required_file.stat.exists == true
