- hosts: master
  gather_facts: no
  tasks:

    - name: Reset firewall rules
      firewalld:
        state: disabled
        port: '{{ item }}'
        permanent: yes
        immediate: yes
      with_items:
        - '6443/tcp'  # Kubernetes API server
        - '2379-2380/tcp'  # etcd server client API
        - '10251/tcp'  # kube-scheduler
        - '10252/tcp'  # kube-controller manager
      ignore_errors: yes  # fails when firewalld is stopped
      become: yes

- hosts: all
  gather_facts: no
  tasks:

    - name: Reset firewall rules
      firewalld:
        state: disabled
        port: '{{ item }}'
        permanent: yes
        immediate: yes
      with_items:
        - '8285/udp'  # Flannel
        - '8472/udp'  # VXLAN backend for Flannel
        - '10250/tcp'  # Kubelet API
        - '30000-32767/tcp'  # NodePort Services
      ignore_errors: yes  # fails when firewalld is stopped
      become: yes
