- hosts: all
  gather_facts: no
  tasks:

    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted
      become: yes

    - name: Install firewall rules
      firewalld:
        state: enabled
        port: '{{ item }}'
        permanent: yes
        immediate: yes
      with_items:
        - '8285/udp'  # Flannel
        - '8472/udp'  # VXLAN backend for Flannel
        - '10250/tcp'  # Kubelet API
        - '30000-32767/tcp'  # NodePort Services
      become: yes

    - name: Enable firewall masquerading
      firewalld:
        state: enabled
        masquerade: true
        permanent: true
        immediate: true
      become: yes

- hosts: master
  gather_facts: no
  tasks:

    - name: Install firewall rules
      firewalld:
        state: enabled
        port: '{{ item }}'
        permanent: yes
        immediate: yes
      with_items:
        - '6443/tcp'  # Kubernetes API server
        - '2379-2380/tcp'  # etcd server client API
        - '10251/tcp'  # kube-scheduler
        - '10252/tcp'  # kube-controller manager
      become: yes
