- hosts: master
  gather_facts: no
  tasks:

    - name: Create namespace for Flannel
      k8s:
        kind: Namespace
        name: kube-flannel
        definition:
          metadata:
            labels:
              pod-security.kubernetes.io/enforce: privileged

    - name: Install Flannel with Helm
      kubernetes.core.helm:
        namespace: kube-flannel
        chart_repo_url: https://flannel-io.github.io/flannel/
        chart_ref: flannel
        chart_version: v0.22.0
        name: flannel
        values:
          podCidr: "{{ pod_network_cidr }}"
