- hosts: masters[0]
  gather_facts: no
  tasks:

    - name: kubeadm init
      shell: |
        kubeadm init \
          --pod-network-cidr={{ pod_network_cidr }} \
          --control-plane-endpoint "{{ ha.vip_hostname }}:{{ ha.port_dest }}" \
          --upload-certs
      become: yes

    - name: Create .kube directory
      file:
        name: /home/{{ ansible_ssh_user }}/.kube/
        state: directory

    - name: Copy kube admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: '/home/{{ ansible_ssh_user }}/.kube/config'
        owner: '{{ ansible_ssh_user }}'
        group: '{{ ansible_ssh_user }}'
        mode: '0600'
        remote_src: True
      become: yes

    - name: Wait for kube API server
      wait_for:
        port: 6443
