- hosts: master
  gather_facts: no
  tasks:

    - name: Generate join cmd
      shell: kubeadm token create --print-join-command
      register: join_cmd

    - name: Save join cmd
      set_fact:
        join_cmd: "{{ join_cmd.stdout }}"

- hosts: workers
  gather_facts: no
  tasks:

    - name: Join cluster
      shell: "{{ hostvars[groups['master'][0]]['join_cmd'] }}"
      become: yes
