- hosts: master
  gather_facts: no
  tasks:

    - name: Get the private IP of the network
      shell: 'ip addr | grep -Po "(?<=inet )((\d+\.){3}\d+)(?=/\d+ .*{{ internal_network_interface }})"'
      register: private_ip

    - name: Create InitConfiguration
      shell: |
        echo '
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: InitConfiguration
        localAPIEndpoint:
          advertiseAddress: "{{ private_ip.stdout }}"
        nodeRegistration:
          kubeletExtraArgs:
            node-ip: "{{ private_ip.stdout }}"
        ---
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: ClusterConfiguration
        networking:
          podSubnet: "{{ pod_network_cidr }}"
        ' > master_InitConfiguration.yaml

    - name: kubeadm init
      shell: kubeadm init --ignore-preflight-errors=NumCPU --config master_InitConfiguration.yaml
      become: yes

    - name: Copy kube admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: '/home/{{ ansible_ssh_user }}/.kube/config'
        owner: '{{ ansible_ssh_user }}'
        group: '{{ ansible_ssh_user }}'
        mode: '0600'
        remote_src: True
      become: yes

    - name: Set bridge
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present

    - name: Wait for kube API server
      wait_for:
        port: 6443
        delay: 10
