- hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Remove old docker packages
      package:
        state: absent
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: '0644'
        force: true

    - name: Get distribution name
      shell: 'echo $(lsb_release -cs)'
      register: dist

    - name: Add Docker Repository
      apt_repository:
        repo: 'deb https://download.docker.com/linux/ubuntu {{ dist.stdout }} stable'
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Run dpkg configure
      shell: 'dpkg --configure -a'

    - name: Install docker packages
      package:
        state: present
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Reset containerd configuration
      file:
        state: absent
        path: /etc/containerd/config.toml

    - name: Create data directory
      file:
        state: directory
        path: /data/docker

    - name: Copy docker daemon.json
      copy:
        src: '{{ playbook_dir }}/config/daemon.json'
        dest: /etc/docker/daemon.json

    - name: Restart containerd
      service:
        name: containerd
        state: restarted

    - name: Restart docker
      service:
        name: docker
        state: restarted
