- hosts: all
  gather_facts: false
  tasks:

    - name: Get IP
      shell: ip route get 1.1.1.1 | sed -n 's/^.*src \([0-9.]*\) .*$/\1/p'
      register: ip

    - name: Store IP
      set_fact:
        ip: "{{ ip.stdout }}"


- hosts: k8s_masters:k8s_workers
  gather_facts: false
  tasks:

    - name: Install system NFS client
      package:
        state: present
        name: nfs-common
      become: yes

- hosts: nfs_server
  gather_facts: false
  tasks:

    - name: Create NFS data directory
      file:
        path: "{{ nfs_export_path }}"
        state: directory
      become: yes

    - name: Create NFS exports file
      ansible.builtin.file:
        path: /etc/exports
        state: touch
      become: yes

    - name: Configure NFS exports
      lineinfile:
        path: '/etc/exports'
        line: '{{ nfs_export_path }} {{ hostvars[item].ip }}(rw,sync,no_root_squash,no_subtree_check)  # {{ hostvars[item].inventory_hostname }}'
        state: 'present'
      with_items: '{{ groups["k8s_masters"] + groups["k8s_workers"] }}'
      become: yes

    - name: Install NFS server
      package:
        state: present
        name: nfs-kernel-server
      become: yes

    - name: Restart nfs-server
      service:
        name: nfs-server
        enabled: true
        state: restarted
      become: yes


- hosts: k8s_masters[0]
  gather_facts: false
  tasks:

    - name: Install NFS provisioner with Helm
      kubernetes.core.helm:
        namespace: nfs-provisioner
        create_namespace: true
        chart_repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
        chart_ref: nfs-subdir-external-provisioner
        name: nfs-provisioner
        values:
          nfs:
            server: '{{ hostvars[groups["nfs_server"][0]].ip }}'
            path: '{{ nfs_export_path }}'
          storageClass:
            name: nfs
            defaultClass: true
            archiveOnDelete: false
